def generate_ci_workflow(features: list, repo_path: str) -> str:
    """
    Generates GitHub Actions workflow YAML and a Python sync script for live stat updates.
    Returns both as a combined string ready to write to .github/workflows/.
    """
    workflow_yaml = f"""name: GodProfile Neural Sync
# Repo: {repo_path or 'your-repo'}
# Features: {', '.join(features) if features else 'stats sync'}
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync_stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run GodProfile Sync
        run: python godprofile_sync.py
        env:
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
      - name: Commit Live Data
        run: |
          git config --global user.name "GodProfile-Bot"
          git config --global user.email "godprofile@bot.com"
          git add assets/
          git commit -m "chore: sync live profile metrics" || exit 0
          git push
"""

    python_scraper = '''"""godprofile_sync.py — Live stat sync script generated by GodProfile MCP."""
import os
import re

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")

def update_svg_placeholders(svg_path: str, replacements: dict) -> None:
    with open(svg_path, encoding="utf-8") as f:
        content = f.read()
    for placeholder, value in replacements.items():
        content = re.sub(rf"<!--\\s*{placeholder}\\s*-->.*?<!--\\s*END\\s*-->",
                         f"<!-- {placeholder} -->{value}<!-- END -->",
                         content, flags=re.DOTALL)
    with open(svg_path, "w", encoding="utf-8") as f:
        f.write(content)

if __name__ == "__main__":
    print("GodProfile sync complete.")
'''

    return (
        f"# === GitHub Actions Workflow ===\n{workflow_yaml}\n"
        f"# === Python Sync Script (godprofile_sync.py) ===\n{python_scraper}"
    )
