"""
Spotify Now Playing module for GodProfile MCP Toolkit.
Provides GitHub Actions workflow generation, SVG card rendering, and live API fetching.
No external dependencies beyond urllib.
"""

import json
import urllib.request
import urllib.error


def _get_theme_tokens(theme_name: str) -> dict:
    try:
        from ..resources import THEMES
        return THEMES.get(theme_name, THEMES["luxury-glass"])
    except Exception:
        return {
            "bg_gradient": ["#0d1117", "#161b22"],
            "accent": "#58a6ff",
            "text": "#c9d1d9",
            "border": "#30363d",
            "font_family_header": "Inter, sans-serif",
            "font_family_data": "JetBrains Mono, monospace",
        }


def setup_spotify_cron(repo: str, client_id: str, client_secret: str) -> str:
    """
    Returns a GitHub Actions YAML string that sets up a cron job to update
    Spotify now-playing SVG every 5 minutes and commits it to the repository.

    Args:
        repo: GitHub repository in the format 'owner/repo'
        client_id: Spotify application client ID
        client_secret: Spotify application client secret

    Returns:
        A complete GitHub Actions workflow YAML string.
    """
    # Build as a plain string — no f-string — to avoid brace-escaping conflicts
    # with the embedded Python script (CSS keyframes, dict literals, f-strings).
    # The repo/client_id/client_secret params are referenced only as a comment;
    # secrets are injected via GitHub Actions secret references in the YAML.
    # repo/client_id/client_secret are stored as GitHub repo secrets by the user;
    # they are documented in the returned YAML as comments only.
    del client_id, client_secret  # not embedded in YAML — stored as repo secrets

    workflow_yaml = (
        "# Generated by GodProfile MCP for repository: " + repo + "\n"
        "name: Spotify Now Playing Sync\n"
        "\n"
        "on:\n"
        "  schedule:\n"
        "    - cron: '*/5 * * * *'\n"
        "  workflow_dispatch:\n"
        "\n"
        "permissions:\n"
        "  contents: write\n"
        "\n"
        "jobs:\n"
        "  update-spotify:\n"
        "    runs-on: ubuntu-latest\n"
        "    name: Update Spotify Now Playing SVG\n"
        "\n"
        "    steps:\n"
        "      - name: Checkout repository\n"
        "        uses: actions/checkout@v4\n"
        "\n"
        "      - name: Set up Python\n"
        "        uses: actions/setup-python@v5\n"
        "        with:\n"
        "          python-version: '3.11'\n"
        "\n"
        "      - name: Fetch Spotify Now Playing and generate SVG\n"
        "        env:\n"
        "          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}\n"
        "          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}\n"
        "          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}\n"
        "        run: |\n"
        "          python - <<'PYEOF'\n"
        "          import urllib.request, urllib.parse, urllib.error, json, base64, os\n"
        "          client_id = os.environ['SPOTIFY_CLIENT_ID']\n"
        "          client_secret = os.environ['SPOTIFY_CLIENT_SECRET']\n"
        "          refresh_token = os.environ['SPOTIFY_REFRESH_TOKEN']\n"
        "          credentials = base64.b64encode((client_id + ':' + client_secret).encode()).decode()\n"
        "          token_data = urllib.parse.urlencode({'grant_type': 'refresh_token', 'refresh_token': refresh_token}).encode()\n"
        "          token_req = urllib.request.Request('https://accounts.spotify.com/api/token', data=token_data,\n"
        "              headers={'Authorization': 'Basic ' + credentials, 'Content-Type': 'application/x-www-form-urlencoded'})\n"
        "          access_token = None\n"
        "          try:\n"
        "              with urllib.request.urlopen(token_req) as resp:\n"
        "                  access_token = json.loads(resp.read().decode())['access_token']\n"
        "          except Exception as e:\n"
        "              print('Token exchange failed:', e)\n"
        "          track, artist, is_playing = None, None, False\n"
        "          if access_token:\n"
        "              api_req = urllib.request.Request(\n"
        "                  'https://api.spotify.com/v1/me/player/currently-playing',\n"
        "                  headers={'Authorization': 'Bearer ' + access_token})\n"
        "              try:\n"
        "                  with urllib.request.urlopen(api_req) as resp:\n"
        "                      if resp.status == 200:\n"
        "                          data = json.loads(resp.read().decode())\n"
        "                          is_playing = data.get('is_playing', False)\n"
        "                          item = data.get('item') or {}\n"
        "                          track = item.get('name', 'Unknown Track')\n"
        "                          artists = item.get('artists', [])\n"
        "                          artist = artists[0].get('name', 'Unknown Artist') if artists else 'Unknown Artist'\n"
        "              except Exception as e:\n"
        "                  print('API error:', e)\n"
        "          bg1, bg2, tc, bc = '#0d1117', '#161b22', '#c9d1d9', '#30363d'\n"
        "          font, mono = 'Inter,sans-serif', 'JetBrains Mono,monospace'\n"
        "          td = (track or 'Unknown')[:32]\n"
        "          ad = (artist or 'Unknown')[:36]\n"
        "          if track and artist and is_playing:\n"
        "              eq = ('<style>@keyframes eq1{0%,100%{height:8px}50%{height:18px}}'\n"
        "                    '@keyframes eq2{0%,100%{height:14px}50%{height:6px}}'\n"
        "                    '@keyframes eq3{0%,100%{height:10px}50%{height:20px}}'\n"
        "                    '.b1{animation:eq1 0.8s ease-in-out infinite}'\n"
        "                    '.b2{animation:eq2 0.9s ease-in-out infinite}'\n"
        "                    '.b3{animation:eq3 0.7s ease-in-out infinite}</style>'\n"
        "                    '<rect class=\"b1\" x=\"34\" y=\"16\" width=\"4\" height=\"8\" rx=\"2\" fill=\"#1db954\"/>'\n"
        "                    '<rect class=\"b2\" x=\"40\" y=\"10\" width=\"4\" height=\"14\" rx=\"2\" fill=\"#1db954\"/>'\n"
        "                    '<rect class=\"b3\" x=\"46\" y=\"14\" width=\"4\" height=\"10\" rx=\"2\" fill=\"#1db954\"/>')\n"
        "              svg = ('<svg width=\"400\" height=\"100\" xmlns=\"http://www.w3.org/2000/svg\">'\n"
        "                     '<defs><linearGradient id=\"bg\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\">'\n"
        "                     '<stop offset=\"0%\" stop-color=\"' + bg1 + '\"/>'\n"
        "                     '<stop offset=\"100%\" stop-color=\"' + bg2 + '\"/></linearGradient></defs>'\n"
        "                     '<rect width=\"400\" height=\"100\" rx=\"12\" fill=\"url(#bg)\" stroke=\"' + bc + '\" stroke-width=\"1\"/>'\n"
        "                     '<rect x=\"0\" y=\"0\" width=\"6\" height=\"100\" rx=\"3\" fill=\"#1db954\"/>'\n"
        "                     '<rect x=\"16\" y=\"8\" width=\"60\" height=\"60\" rx=\"8\" fill=\"#1db954\" opacity=\"0.12\"/>'\n"
        "                     '<text x=\"44\" y=\"47\" font-size=\"26\" text-anchor=\"middle\" fill=\"#1db954\">&#9835;</text>'\n"
        "                     + eq +\n"
        "                     '<text x=\"86\" y=\"34\" font-family=\"' + font + '\" font-size=\"14\" font-weight=\"700\" fill=\"' + tc + '\">' + td + '</text>'\n"
        "                     '<text x=\"86\" y=\"52\" font-family=\"' + font + '\" font-size=\"11\" fill=\"' + tc + '\" opacity=\"0.55\">' + ad + '</text>'\n"
        "                     '<text x=\"86\" y=\"80\" font-family=\"' + mono + '\" font-size=\"9\" fill=\"#1db954\" opacity=\"0.75\">Now Playing on Spotify</text>'\n"
        "                     '</svg>')\n"
        "          else:\n"
        "              svg = ('<svg width=\"400\" height=\"100\" xmlns=\"http://www.w3.org/2000/svg\">'\n"
        "                     '<defs><linearGradient id=\"bg\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\">'\n"
        "                     '<stop offset=\"0%\" stop-color=\"' + bg1 + '\"/>'\n"
        "                     '<stop offset=\"100%\" stop-color=\"' + bg2 + '\"/></linearGradient></defs>'\n"
        "                     '<rect width=\"400\" height=\"100\" rx=\"12\" fill=\"url(#bg)\" stroke=\"' + bc + '\" stroke-width=\"1\"/>'\n"
        "                     '<rect x=\"0\" y=\"0\" width=\"6\" height=\"100\" rx=\"3\" fill=\"#1db954\" opacity=\"0.4\"/>'\n"
        "                     '<rect x=\"16\" y=\"8\" width=\"60\" height=\"60\" rx=\"8\" fill=\"#333\" opacity=\"0.5\"/>'\n"
        "                     '<text x=\"44\" y=\"47\" font-size=\"26\" text-anchor=\"middle\" fill=\"#555\">&#9835;</text>'\n"
        "                     '<text x=\"86\" y=\"42\" font-family=\"' + font + '\" font-size=\"13\" fill=\"' + tc + '\" opacity=\"0.5\">Not currently playing</text>'\n"
        "                     '<text x=\"86\" y=\"62\" font-family=\"' + mono + '\" font-size=\"9\" fill=\"#1db954\" opacity=\"0.5\">Listening on Spotify</text>'\n"
        "                     '</svg>')\n"
        "          with open('spotify.svg', 'w', encoding='utf-8') as f:\n"
        "              f.write(svg)\n"
        "          print('spotify.svg written.')\n"
        "          PYEOF\n"
        "\n"
        "      - name: Commit and push SVG\n"
        "        run: |\n"
        "          git config --local user.email \"github-actions[bot]@users.noreply.github.com\"\n"
        "          git config --local user.name \"github-actions[bot]\"\n"
        "          git add spotify.svg\n"
        "          git diff --cached --quiet || git commit -m \"chore: update Spotify now-playing SVG [skip ci]\"\n"
        "          git push\n"
    )
    return workflow_yaml


def render_now_playing(
    track: str = None,
    artist: str = None,
    theme: str = "luxury-glass",
    is_playing: bool = True,
) -> str:
    """
    Returns a 400x100 SVG 'Now Playing' card.

    Features:
    - Spotify green (#1db954) accent bar on the left edge
    - Animated equalizer bars (CSS keyframes) when is_playing=True, static when False
    - Track title in bold, artist name in muted color
    - 'Listening on Spotify' footer text
    - Album art placeholder (rounded rect with music note icon)
    - Theme tokens applied for background and text colors

    Args:
        track: Track name (defaults to placeholder if None)
        artist: Artist name (defaults to placeholder if None)
        theme: GodProfile theme name
        is_playing: Whether a track is actively playing

    Returns:
        SVG string.
    """
    tokens = _get_theme_tokens(theme)
    bg1 = tokens["bg_gradient"][0]
    bg2 = tokens["bg_gradient"][1] if len(tokens["bg_gradient"]) > 1 else tokens["bg_gradient"][0]
    text_color = tokens["text"]
    border_color = tokens["border"]
    font = tokens["font_family_header"]
    mono = tokens["font_family_data"]

    track_display = (track or "Unknown Track")[:32]
    if track and len(track) > 32:
        track_display += "..."

    artist_display = (artist or "Unknown Artist")[:36]
    if artist and len(artist) > 36:
        artist_display += "..."

    if is_playing:
        equalizer = """
    <style>
      @keyframes eq1 { 0%,100%{height:8px} 50%{height:18px} }
      @keyframes eq2 { 0%,100%{height:14px} 33%{height:6px} 66%{height:18px} }
      @keyframes eq3 { 0%,100%{height:10px} 50%{height:20px} }
    </style>
    <rect x="34" y="16" width="4" rx="2" height="8" fill="#1db954" style="animation:eq1 0.8s ease-in-out infinite;transform-origin:34px 24px"/>
    <rect x="40" y="10" width="4" rx="2" height="14" fill="#1db954" style="animation:eq2 0.9s ease-in-out infinite;transform-origin:40px 24px"/>
    <rect x="46" y="14" width="4" rx="2" height="10" fill="#1db954" style="animation:eq3 0.7s ease-in-out infinite;transform-origin:46px 24px"/>"""
    else:
        equalizer = """
    <rect x="34" y="18" width="4" rx="2" height="4" fill="#1db954" opacity="0.4"/>
    <rect x="40" y="16" width="4" rx="2" height="8" fill="#1db954" opacity="0.4"/>
    <rect x="46" y="20" width="4" rx="2" height="4" fill="#1db954" opacity="0.4"/>"""

    now_playing_label = "Now Playing" if is_playing else "Last Played"

    svg = f"""<svg width="400" height="100" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bgGrad" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="{bg1}"/>
      <stop offset="100%" stop-color="{bg2}"/>
    </linearGradient>
    <clipPath id="cardClip">
      <rect width="400" height="100" rx="12"/>
    </clipPath>
  </defs>

  <!-- Background -->
  <rect width="400" height="100" rx="12" fill="url(#bgGrad)" stroke="{border_color}" stroke-width="1"/>

  <!-- Spotify accent bar -->
  <rect x="0" y="0" width="6" height="100" rx="3" fill="#1db954"/>

  <!-- Album art placeholder -->
  <rect x="16" y="14" width="56" height="56" rx="8" fill="#1db954" opacity="0.12" stroke="#1db954" stroke-width="1" stroke-opacity="0.3"/>
  <text x="44" y="49" font-size="26" text-anchor="middle" fill="#1db954" opacity="0.7">&#9835;</text>

  <!-- Equalizer bars -->
  {equalizer}

  <!-- Track info -->
  <text x="86" y="34" font-family="{font}" font-size="14" font-weight="700" fill="{text_color}">{track_display}</text>
  <text x="86" y="52" font-family="{font}" font-size="11" fill="{text_color}" opacity="0.55">{artist_display}</text>

  <!-- Footer -->
  <text x="86" y="80" font-family="{mono}" font-size="9" fill="#1db954" opacity="0.75">{now_playing_label} · Listening on Spotify</text>

  <!-- Spotify logo dot -->
  <circle cx="380" cy="82" r="5" fill="#1db954" opacity="0.6"/>
</svg>"""

    return svg


def fetch_now_playing(access_token: str, theme: str = "luxury-glass") -> str:
    """
    Fetches the currently playing track from Spotify API and returns an SVG card.

    Uses urllib only (no external dependencies).
    On any error or 204 No Content response, returns a 'Not Playing' card.

    Args:
        access_token: A valid Spotify OAuth access token.
        theme: GodProfile theme name for the SVG card.

    Returns:
        SVG string via render_now_playing().
    """
    url = "https://api.spotify.com/v1/me/player/currently-playing"
    req = urllib.request.Request(
        url,
        headers={"Authorization": f"Bearer {access_token}"},
    )

    try:
        with urllib.request.urlopen(req) as response:
            if response.status == 204:
                # No content — nothing playing
                return render_now_playing(theme=theme, is_playing=False)

            raw = response.read().decode("utf-8")
            data = json.loads(raw)

            is_playing = data.get("is_playing", False)
            item = data.get("item") or {}

            track = item.get("name") or "Unknown Track"
            artists = item.get("artists") or []
            artist = artists[0].get("name", "Unknown Artist") if artists else "Unknown Artist"

            return render_now_playing(
                track=track,
                artist=artist,
                theme=theme,
                is_playing=is_playing,
            )

    except urllib.error.HTTPError as e:
        if e.code == 204:
            return render_now_playing(theme=theme, is_playing=False)
        # Auth error or other HTTP failure — return not playing card
        return render_now_playing(
            track="Spotify Unavailable",
            artist=f"HTTP {e.code}",
            theme=theme,
            is_playing=False,
        )

    except urllib.error.URLError:
        return render_now_playing(
            track="Network Error",
            artist="Could not reach Spotify",
            theme=theme,
            is_playing=False,
        )

    except (json.JSONDecodeError, KeyError):
        return render_now_playing(theme=theme, is_playing=False)
